spring:
  application:
    name: gitmanager
  datasource:
    url: jdbc:mysql://localhost:3306/gitmanager?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 604800000

jasypt:
  encryptor:
    password: ${AES_SECRET_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173

cookie:
  secure: false

server:
  port: 8080